apiVersion: batch/v1
kind: Job
metadata:
  namespace: "{{JOB_NAMESPACE}}"
  generateName: obelisk-fluid-
  annotations:
    launched_by_user: "{{LAUNCHED_BY_USER}}"
    launched_by_hostname: "{{LAUNCHED_BY_HOSTNAME}}"
spec:
  template:
    metadata:
      annotations:
        launched_by_user: "{{LAUNCHED_BY_USER}}"
        launched_by_hostname: "{{LAUNCHED_BY_HOSTNAME}}"
    spec:
      containers:
        - name: fluid
          image: astera-infra.com/fluid
          command:
            - "bash"
            - "-c"
            - 'cd fluid && eval "$(pixi shell-hook)" && python --version && pwd'
          env:
            - name: GIT_PYTHON_REFRESH
              value: quiet
          volumeMounts:
            - name: databrickscfg
              mountPath: "/root/.databrickscfg"
              subPath: ".databrickscfg"
              readOnly: true
          resources:
            limits:
              nvidia.com/gpu: "{{GPU_COUNT}}"
      volumes:
        - name: databrickscfg
          secret:
            secretName: databrickscfg
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
