[package]
name = "container-image-name"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9"
serde = { version = "1.0.201", optional = true }

[dev-dependencies]
serde_json = "1.0.117"

[features]
default = ["serde"]
serde = ["dep:serde"]
